WebDemo14112023/Areas/Admin/Controllers/NewsCategoryController.cs
using DatabaseFirstDemo.Models;
using DatabaseFirstDemo.Repository;
using Microsoft.AspNetCore.Mvc;

namespace WebDemo14112023.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewsCategoryController : BaseController
    {
        INewsCategoryRepository newsCategoryRepository = null;
        public NewsCategoryController()
        {
            newsCategoryRepository = new NewsCategoryRepository();
        }

        public IActionResult Index()
        {
            /*ProductMangementBatch177Context _context = new ProductMangementBatch177Context();
            var list = _context.NewsCategories.ToList();*/
            var result = newsCategoryRepository.GetAll();
            return View(result);
        }

        // GET: Admin/Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Create(NewsCategory newCategory)
        {
            try
            {
       /*         if (ModelState.IsValid)
                {*/
                    newsCategoryRepository.Insert(newCategory);
                    SetAlert("Insert Data is success!", "success");
                    return Json(new { success = true });
                /*}*/
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = false });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            NewsCategory newCategory = newsCategoryRepository.GetById(id);
            var data = new
            {
                Id = newCategory.Id,
                Name = newCategory.CategoryName
                // Các trường khác
            };

            return new JsonResult(new { success = true, data = data });
        }

        [HttpPost]
        public JsonResult Edit(NewsCategory newCategory)
        {
            try
            {
              /*  if (ModelState.IsValid)
                {*/
                    newsCategoryRepository.Update(newCategory);
                    SetAlert("Update Data is success!", "success");
                /*}*/
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = true });
        }

        [HttpPost]
        public JsonResult Delete(NewsCategory newCategory)
        {
            try
            {
                newsCategoryRepository.Delete(newCategory);
                SetAlert("Delete Data is success!", "success");
                
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = true });
        }

    }
}

WebDemo14112023/Areas/Admin/Controllers/RolesController.cs
using DatabaseFirstDemo.Models;
using DatabaseFirstDemo.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebDemo14112023.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesController : BaseController
    {
        private readonly ProductMangementBatch177Context _context;

        IRolesRepository rolesRepository = null;
        public RolesController()
        {
            rolesRepository = new RolesRepository();
        }


        // GET: Admin/Roles
        public IActionResult Index()
        {
            var result = rolesRepository.GetAll();
            return View(result);
            /* return result != null ?
                          View(await result) :
                          Problem("Entity set 'ProductMangementBatch177Context.Roles'  is null.");*/
        }

        // GET: Admin/Roles/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Admin/Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Create(Role role)
        {
            try
            {
                /*         if (ModelState.IsValid)
                         {*/
                rolesRepository.Insert(role);
                SetAlert("Insert Data is success!", "success");
                return Json(new { success = true });
                /*}*/
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = false });
        }

        // GET: Admin/Roles/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Role role = rolesRepository.GetById(id);
            var data = new
            {
                Id = role.Id,
                Name = role.Name
                // Các trường khác
            };

            return new JsonResult(new { success = true, data = data });
        }

        [HttpPost]
        public JsonResult Edit(Role role)
        {
            try
            {
                /*  if (ModelState.IsValid)
                  {*/
                rolesRepository.Update(role);
                SetAlert("Update Data is success!", "success");
                /*}*/
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = true });
        }

        [HttpPost]
        public JsonResult Delete(Role role)
        {
            try
            {
                rolesRepository.Delete(role);
                SetAlert("Delete Data is success!", "success");

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = true });
        }

        private bool RoleExists(int id)
        {
            return (_context.Roles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebDemo14112023/Areas/Admin/Controllers/UsersController.cs
using DatabaseFirstDemo.DAO;
using DatabaseFirstDemo.Models;
using DatabaseFirstDemo.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using WebDemo14112023.Areas.Admin.Models;

namespace WebDemo14112023.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : BaseController
    {
        IUsersRepository userRepository = null;
        IRolesRepository roleRepository = null;
        public UsersController()
        {
            userRepository = new UsersRepository();
            roleRepository = new RolesRepository();
        }
        public IActionResult Index()
        {
            // Lấy danh sách quyền truy cập từ Repository hoặc Database
            IEnumerable<Role> roles = roleRepository.GetAll();

            // Tạo SelectList từ danh sách quyền truy cập
            SelectList selectList = new SelectList(roles, "Id", "Name");

            // Lưu SelectList vào ViewBag để sử dụng trong View
            ViewBag.Roles = selectList;

            IEnumerable<User> users = userRepository.GetAll();
            IEnumerable<UserDetail> usersdetail = userRepository.GetUserDetailAll();
            return View(new RoleUser
            {
                Roles = (ICollection<Role>)roles,
                Users = (ICollection<User>)users,
                UserDetails = (ICollection<UserDetail>)usersdetail,
            });
            //return View(users);
        }

        // GET: Admin/Roles/Create
        public IActionResult Create()
        {
            ViewBag.Roles = new SelectList(userRepository.GetAllRoles(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public JsonResult Create(User users, UserDetail userDetails)
        {
            try
            {
                // Lấy giá trị từ các trường thuộc tính của user trong form
                var user = new User
                {
                    UserName = users.UserName,
                    Password = Common.Common.EncryptMD5(users.Password),
                    RoleId = users.RoleId,
                    Status = users.Status
                };

                // Lấy giá trị từ các trường thuộc tính của userDetail trong form
                var userDetail = new UserDetail
                {
                    FullName = userDetails.FullName,
                    Address = userDetails.Address,
                    Email = userDetails.Email
                };
                /*  if (ModelState.IsValid)
                  {*/
                userRepository.InsertUser(user);
                // Gán giá trị UserId mới tạo cho thuộc tính UserId của userDetail
                userDetail.UserId = user.UserId;
                userRepository.InsertUserDetail(userDetail);
                SetAlert("Insert Data is success!", "success");
                    return Json(new { success = true });
               /* }*/
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = false });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            User user = userRepository.GetById(id);
            UserDetail userDetail = userRepository.GetByUserDetailId(id);
            ViewBag.Roles = new SelectList(roleRepository.GetAll(), "Id", "Name", user.RoleId);
            var data = new
            {
                Id = user.UserId,
                UserName = user.UserName,
                //Password = user.Password,
                Status = user.Status,
                RoleId = user.RoleId,
                FullName = userDetail.FullName,
                Address = userDetail.Address,
                Email = userDetail.Email
                // Các trường khác
            };

            return new JsonResult(new { success = true, data = data });
        }

        [HttpPost]
        public JsonResult Edit(User users, UserDetail userDetails)
        {
            try
            {
                // Lấy giá trị từ các trường thuộc tính của user trong form
                var user = new User
                {
                    UserId = users.UserId,
                    UserName = users.UserName,
                    RoleId = users.RoleId,
                    Status = users.Status
                };
                if(users.Password != null){
                    user.Password = Common.Common.EncryptMD5(users.Password);
                }
                else
                {
                    user.Password = userRepository.GetById(users.UserId).Password;
                }
                // Lấy giá trị từ các trường thuộc tính của userDetail trong form
                var userDetail = new UserDetail
                {
                    UserId = userDetails.UserId,
                    FullName = userDetails.FullName,
                    Address = userDetails.Address,
                    Email = userDetails.Email
                };
                userRepository.UpdateUser(user);
                userRepository.UpdateUserDetail(userDetail);
                SetAlert("Update Data is success!", "success");
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = false });
        }

        [HttpPost]
        public JsonResult Delete(User user)
        {
            try
            {
                userRepository.Delete(user);
                SetAlert("Delete Data is success!", "success");
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
            return Json(new { success = true });
        }

        [HttpPost]
        public JsonResult ChangeStatus(int id)
        {
            var result = userRepository.ChangeStatus(id);
            return Json(new
            {
                status = result
            });
        }
    }
}

WebDemo14112023/Areas/Admin/Views/Shared/_Header.cshtml
<header class="header fixed-top clearfix">
    <!--logo start-->
    <div class="brand">

        <a href="index.html" class="logo">
            <img src="~/admin/images/logo.png" alt="">
        </a>
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars"></div>
        </div>
    </div>
    <!--logo end-->

    <div class="nav notify-row" id="top_menu">
        <!--  notification start -->
        <ul class="nav top-menu">
            <!-- settings start -->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="fa fa-tasks"></i>
                    <span class="badge bg-success">8</span>
                </a>
                <ul class="dropdown-menu extended tasks-bar">
                    <li>
                        <p class="">You have 8 pending tasks</p>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Target Sell</h5>
                                    <p>25% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="45">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Product Delivery</h5>
                                    <p>45% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="78">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Payment collection</h5>
                                    <p>87% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="60">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Target Sell</h5>
                                    <p>33% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="90">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>

                    <li class="external">
                        <a href="#">See All Tasks</a>
                    </li>
                </ul>
            </li>
            <!-- settings end -->
            <!-- inbox dropdown start-->
            <li id="header_inbox_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-important">4</span>
                </a>
                <ul class="dropdown-menu extended inbox">
                    <li>
                        <p class="red">You have 4 Mails</p>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/admin/images/avatar-mini.jpg"></span>
                            <span class="subject">
                                <span class="from">Jonathan Smith</span>
                                <span class="time">Just now</span>
                            </span>
                            <span class="message">
                                Hello, this is an example msg.
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/admin/images/avatar-mini-2.jpg"></span>
                            <span class="subject">
                                <span class="from">Jane Doe</span>
                                <span class="time">2 min ago</span>
                            </span>
                            <span class="message">
                                Nice admin template
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/admin/images/avatar-mini-3.jpg"></span>
                            <span class="subject">
                                <span class="from">Tasi sam</span>
                                <span class="time">2 days ago</span>
                            </span>
                            <span class="message">
                                This is an example msg.
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="~/admin/images/avatar-mini.jpg"></span>
                            <span class="subject">
                                <span class="from">Mr. Perfect</span>
                                <span class="time">2 hour ago</span>
                            </span>
                            <span class="message">
                                Hi there, its a test
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">See all messages</a>
                    </li>
                </ul>
            </li>
            <!-- inbox dropdown end -->
            <!-- notification dropdown start-->
            <li id="header_notification_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                    <i class="fa fa-bell-o"></i>
                    <span class="badge bg-warning">3</span>
                </a>
                <ul class="dropdown-menu extended notification">
                    <li>
                        <p>Notifications</p>
                    </li>
                    <li>
                        <div class="alert alert-info clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #1 overloaded.</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="alert alert-danger clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #2 overloaded.</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="alert alert-success clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #3 overloaded.</a>
                            </div>
                        </div>
                    </li>

                </ul>
            </li>
            <!-- notification dropdown end -->
        </ul>
        <!--  notification end -->
    </div>
    <div class="top-nav clearfix">
        <!--search & user info start-->
        <ul class="nav pull-right top-menu">
            <li>
                <input type="text" class="form-control search" placeholder=" Search">
            </li>
            <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <img alt="" src="~/admin/images/avatar1_small.jpg">
                    <span class="username">John Doe</span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                    <li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                    <li><a href="login.html"><i class="fa fa-key"></i> Log Out</a></li>
                </ul>
            </li>
            <!-- user login dropdown end -->
            <li>
                <div class="toggle-right-box">
                    <div class="fa fa-bars"></div>
                </div>
            </li>
        </ul>
        <!--search & user info end-->
    </div>
</header>

WebDemo14112023/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="images/favicon.png">
    <title>@ViewData["Title"] - Demo</title>
    <!--Core CSS -->
    <link href="~/admin/bs3/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/admin/js/jquery-ui/jquery-ui-1.10.1.custom.min.css" rel="stylesheet">
    <link href="~/admin/css/bootstrap-reset.css" rel="stylesheet">
    <link href="~/admin/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/admin/js/jvector-map/jquery-jvectormap-1.2.2.css" rel="stylesheet">
    <link href="~/admin/css/clndr.css" rel="stylesheet">
    <!--clock css-->
    <link href="~/admin/js/css3clock/css/style.css" rel="stylesheet">
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="~/admin/js/morris-chart/morris.css">
    <!-- Custom styles for this template -->
    <link href="~/admin/css/style.css" rel="stylesheet">
    <link href="~/admin/css/style-responsive.css" rel="stylesheet" />
    <!-- Just for debugging purposes. Don't actually copy this line! -->
</head>
<body>
    <section id="container">
        <!--header start-->
        @Html.Partial("_Header")
        <!--header end-->
        <!--sidebar start-->
        @Html.Partial("_MenuLeft")
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">
               @RenderBody()
            </section>
        </section>
        <!--main content end-->
        <!--right sidebar start-->
        @Html.Partial("_MenuRight")
        <!--right sidebar end-->
    </section>
    <!-- Placed js at the end of the document so the pages load faster -->
    <!--Core js-->
    <script src="~/admin/js/jquery.js"></script>
    <script src="~/admin/js/jquery-ui/jquery-ui-1.10.1.custom.min.js"></script>
    <script src="~/admin/bs3/js/bootstrap.min.js"></script>
    <script src="~/admin/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/admin/js/jquery.scrollTo.min.js"></script>
    <script src="~/admin/js/jQuery-slimScroll-1.3.0/jquery.slimscroll.js"></script>
    <script src="~/admin/js/jquery.nicescroll.js"></script>
    <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
    <script src="~/admin/js/skycons/skycons.js"></script>
    <script src="~/admin/js/jquery.scrollTo/jquery.scrollTo.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="~/admin/js/calendar/clndr.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js"></script>
    <script src="~/admin/js/calendar/moment-2.2.1.js"></script>
    <script src="~/admin/js/evnt.calendar.init.js"></script>
    <script src="~/admin/js/jvector-map/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/admin/js/jvector-map/jquery-jvectormap-us-lcc-en.js"></script>
    <script src="~/admin/js/gauge/gauge.js"></script>
    <!--clock init-->
    <script src="~/admin/js/css3clock/js/css3clock.js"></script>
    <!--Easy Pie Chart-->
    <script src="~/admin/js/easypiechart/jquery.easypiechart.js"></script>
    <!--Sparkline Chart-->
    <script src="~/admin/js/sparkline/jquery.sparkline.js"></script>
    <!--Morris Chart-->
    <script src="~/admin/js/morris-chart/morris.js"></script>
    <script src="~/admin/js/morris-chart/raphael-min.js"></script>
    <!--jQuery Flot Chart-->
    <script src="~/admin/js/flot-chart/jquery.flot.js"></script>
    <script src="~/admin/js/flot-chart/jquery.flot.tooltip.min.js"></script>
    <script src="~/admin/js/flot-chart/jquery.flot.resize.js"></script>
    <script src="~/admin/js/flot-chart/jquery.flot.pie.resize.js"></script>
    <script src="~/admin/js/flot-chart/jquery.flot.animator.min.js"></script>
    <script src="~/admin/js/flot-chart/jquery.flot.growraf.js"></script>
@*     <script src="~/admin/js/dashboard.js"></script> *@
    <script src="~/admin/js/jquery.customSelect.min.js"></script>
    <!--common script init for all pages-->
    <script src="~/admin/js/scripts.js"></script>
    <!--script for this page-->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebDemo14112023/Areas/Admin/Views/Shared/_MenuLeft.cshtml
<aside>
    <div id="sidebar" class="nav-collapse">
        <!-- sidebar menu start-->
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="index.html">
                        <i class="fa fa-dashboard"></i>
                        <span>Trang quản trị</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Danh mục</span>
                    </a>
                    <ul class="sub">
                        <li><a href="general.html"><i class="fa fa-folder-o"></i>Danh mục Loại Sản phẩm</a></li>
                        <li><a asp-action="Index" asp-controller="NewsCategory"><i class="fa fa-folder-o"></i>Danh mục Loại Tin tức</a></li>
                        <li><a asp-action="Index" asp-controller="Roles"><i class="fa fa-folder-o"></i>Danh mục Phân quyền</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Quản lý</span>
                    </a>
                    <ul class="sub">
                        <li><a href="general.html"><i class="fa fa-folder-o"></i>Danh mục Loại Sản phẩm</a></li>
                        <li><a href="buttons.html"><i class="fa fa-folder-o"></i>Danh mục Loại Tin tức</a></li>
                        <li><a asp-action="Index" asp-controller="Users"><i class="fa fa-folder-o"></i>Quản lý người dùng</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Báo cáo & Thống kê</span>
                    </a>
                    <ul class="sub">
                        <li><a href="general.html"><i class="fa fa-folder-o"></i>Danh mục Loại Sản phẩm</a></li>
                        <li><a href="buttons.html"><i class="fa fa-folder-o"></i>Danh mục Loại Tin tức</a></li>
                        <li><a href="typography.html"><i class="fa fa-folder-o"></i>Danh mục Loại Thông báo</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-book"></i>
                        <span>Cấu hình</span>
                    </a>
                    <ul class="sub">
                        <li><a href="general.html"><i class="fa fa-folder-o"></i>Danh mục Loại Sản phẩm</a></li>
                        <li><a href="buttons.html"><i class="fa fa-folder-o"></i>Danh mục Loại Tin tức</a></li>
                        <li><a href="typography.html"><i class="fa fa-folder-o"></i>Danh mục Loại Thông báo</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- sidebar menu end-->
    </div>
</aside>